version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kyskfilms-postgres
    environment:
      POSTGRES_DB: kyskfilms_db
      POSTGRES_USER: kysk_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - kyskfilms-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: kyskfilms-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB: postgres
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
#    volumes:
#      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db
    networks:
      - kyskfilms-network

  keycloak-db:
    image: postgres:15
    container_name: kyskfilms-keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./volumes/keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - kyskfilms-network

  app:
    build: .
    container_name: kyskfilms-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kyskfilms_db
      SPRING_DATASOURCE_USERNAME: kysk_user
      SPRING_DATASOURCE_PASSWORD: your_secure_password
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/kyskfilms
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/kyskfilms/protocol/openid-connect/certs
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: kyskfilms
      KEYCLOAK_RESOURCE: kyskfilms-backend
      JWT_SECRET: change_me_to_a_very_long_and_secure_secret_key_at_least_32chars_long_please
    depends_on:
      - postgres
      - keycloak
    networks:
      - kyskfilms-network

volumes:
  postgres_data:
  keycloak_postgres_data:

networks:
  kyskfilms-network:
    driver: bridge